### ISSUE TITLE
Transfer money on death to server account

### ISSUE THREAD

**Issue by Bloodlex** [Whawhatausore/DeathPenalties#18]
Hello,
Could you please add an option to transfer money lost after death to the specified account? For instance:

server-account: tax

And then this money would go to tax.

Thanks a lot!
Best regards

**Comment by Whawhatausore** [comment]
Hello,
Thanks for your idea. I will add it in the next plugin fix update!

**Comment by Bloodlex** [comment]
@Whawhatausore 
Hello,

Good to hear! Thank you very much, great plugin by the way! :)

Best regards

**Comment by Whawhatausore** [comment]
It has now been implemented and will be available when the next update is out.

**Comment by Bloodlex** [comment]
@Whawhatausore thanks a lot, you're the best! 👍
