### ISSUE TITLE
MobArena integration doesn't work

### ISSUE THREAD

**Issue by Bloodlex** [Whawhatausore/DeathPenalties#21]
Amazing plugin, but I have one serious problem: integration with MobArena doesn't work and it charges my players money from dying and also leaves them with lowered hunger and health. Could you please fix that? Without that it makes my MobArena unusable actually.

**Comment by Whawhatausore** [comment]
Issue has been fixed for the 1.5.1 update

**Comment by Bloodlex** [comment]
Thanks a lot, works fine now👍
