### ISSUE TITLE
Penalty when exiting The End via End Portal without dying

### ISSUE THREAD

**Issue by Bloodlex** [Whawhatausore/DeathPenalties#25]
Hello,

I have a problem that the player is penalized when exiting The End via Portal without dying. Could you take a look on that please? 🙁 It can also affect Nether, but I'm not sure with that.

My config file:
[https://pastebin.com/NxSD1D6j](https://pastebin.com/NxSD1D6j)

Best regards,
Bloodlex

**Comment by Whawhatausore** [comment]
Sorry, I am super busy with work right now and can't fix it as fast as possible. I tested it now, it's only happening for the respawn penalties after you took the end portal. I will fix it this weekend.

Thanks for submitting the issue.

**Comment by Bloodlex** [comment]
@Whawhatausore Thank you very much! I'm really looking forward to it! 🙂 👍

**Comment by Whawhatausore** [comment]
Fixed in released update 1.5.3

**Comment by Bloodlex** [comment]
@Whawhatausore Thank you very much, you're the best! 🙂 👍
